name: mkdocs

on:
  workflow_run:
    workflows: ["tailwindcss-update"]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force --clean --config-file ./mkdocs.yml --site-dir ./useful-resources
