name: mkdocs

on:
  workflow_run:
    workflows: ["tailwindcss-update"]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build --site-dir ./useful-resources
      
      - name: push changes
        run: |
          git add --force useful-resources/\*
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -sm "Update Mkdocs"
          git push
