name: setup

on:
  push:
    branches:
      - main

jobs:          
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: update mkdocs
        uses: actions/setup-python@v5
        with:
          python-version: 3.x      
      - run: pip install mkdocs-material
      - run: mkdocs build --site-dir ./useful-resources
          
      - name: push changes
        run: |
          git add --force useful-resources/\*
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -sm "setup"
          git push
